title: olivermak.es
author:
  name: Oliver Pattison
  email: oliverpattison@gmail.com
  twitter: '@olivermakes'
description: 'I am Oliver Pattison, a designer focused on the future of the web.'

license:
  short: 'CC BY-NC 4.0'
  long: 'Creative Commons Attribution-NonCommercial 4.0 International'

# Content

## Referenced URLs (internal and external links for inline use)
link:
  attribution: http://creativecommons.org/licenses/by-nc/4.0/
  flickr: https://www.flickr.com/photos/ok-oyot
  jean: http://jeancflanagan.com
  github: https://github.com/opattison
  googleplus: http://plus.google.com/+OliverPattison
  panoramio: http://www.panoramio.com/user/oliverpattison
  pinboard: https://pinboard.in/u:opattison
  source: http://github.com/opattison/olivermakes
  subscribe:
    full: http://olivermak.es/full.xml
    writing: http://olivermak.es/writing/feed.xml
    photography: http://olivermak.es/photography/feed.xml
    projects: http://olivermak.es/projects/feed.xml
  tumblr: http://olivermakes.tumblr.com
  twitter: http://twitter.com/olivermakes
  vsco: http://olivermakes.vsco.co

## Collections

collections:
  patterns:
    output: true
    permalink: patterns/:path/

# Site configuration

## Gems configuration
gems:
  - jekyll-archives
  - sass

## Markdown configuration
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  footnote_backlink: '&#8638;'

## Permalink configuration
permalink: /:year/:month/:title/

## Jekyll Archives configuration
jekyll-archives:
  enabled:
    - year
    - month
    - categories
    - tags
  layouts:
    year: archive-time
    month: archive-time
    category: archive-category
    tag: archive-tag
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    tag: '/label/:name/'
    category: '/:name/archive/'

## Sass configuration
sass:
  sass_dir: _sass
  style: compressed

## Project configuration
exclude: [s3_website.yml, Rakefile]

## Configuration URLs
domain: olivermak.es
url: http://olivermak.es
patterns_url: /patterns
image_url: /resources/images
icon_url: /resources/icons
style_url: /resources/style
script_url: /resources/scripts
fragments_url: /resources/fragments
source_url:
  repo: https://github.com/opattison/olivermakes
  blob: https://github.com/opattison/olivermakes/blob/master
  commits: https://github.com/opattison/olivermakes/commits/master

## srcset implementation
wide-sizes: '(min-width: 140em) 1440px, (min-width: 115em) 1260px, (min-width: 95em) 1080px, (min-width: 60em) 900px, (min-width: 45em) 720px, 100vw'
grid2-sizes: '(min-width: 140em) 691px, (min-width: 115em) 605px, (min-width: 95em) 518px, (min-width: 60em) 432px, (min-width: 45em) 720px, 100vw'
project-sizes: '(min-width: 115em) 756px, (min-width: 90em) 648px, (min-width: 70em) 540px, (min-width: 60em) 740px, (min-width: 45em) 620px, (min-width: 30em) calc(100vw - 4em), calc(100vw - 2em)'
srcset1440:
  - 480
  - 640
  - 720
  - 900
  - 1080
  - 1260
  - 1440
srcset1080:
  - 480
  - 640
  - 720
  - 900
  - 1080
srcset_project:
  - 480
  - 720
  - 1080

## Mapbox authentication and configuration
mapbox_key: pk.eyJ1Ijoib3BhdHRpc29uIiwiYSI6Il9DU3p1MEkifQ.3cvRQB5hVIONMpDAflBUNw
photo_mapid: opattison.942a5f69

## Google site verification
google_verification: v50CkzaVPDL_gBaZnlGdxJmfnZDYCP74l1JTMgLsyp4
